//////////////////////////////////////////////////////////////////
//								//
// Copyright (c) 2018-2022 YottaDB LLC and/or its subsidiaries.	//
// All rights reserved.						//
//								//
//	This source code contains the intellectual property	//
//	of its copyright holder(s), and is made available	//
//	under a license.  If you do not know the terms of	//
//	the license, please stop and do not read further.	//
//								//
//////////////////////////////////////////////////////////////////
// Code generated by go generate; DO NOT EDIT.
// Note: The above line is copy-pasted from error_codes.go and is needed as a temporary workaround
// to avoid warnings like the following from golint which otherwise shows up on the below YDB_ERR_* const codes.
//        error_local.go:21:2: don't use ALL_CAPS in Go names; use CamelCase

package yottadb

// Global constants containing the error ids
const (
	YDB_ERR_STRUCTUNALLOCD  = -151552010
	YDB_ERR_INVLKNMPAIRLIST = -151552018
	YDB_ERR_DBRNDWNBYPASS   = -151552026
	YDB_ERR_SIGACKTIMEOUT   = -151552034
	YDB_ERR_SIGGORTNTIMEOUT = -151552040
)

// ydbGoErrors is an array of error entries containing the Go-only set of errors
var ydbGoErrors = []ydbGoErrEntry{
	{-YDB_ERR_STRUCTUNALLOCD, "E", "STRUCTNUNALLOCD", "Structure not previously called with Alloc() method"},
	{-YDB_ERR_INVLKNMPAIRLIST, "E", "INVLKNMPAIRLIST",
		"Invalid lockname/subscript pair list (uneven number of lockname/subscript parameters)"},
	{-YDB_ERR_DBRNDWNBYPASS, "DBRNDWNBYPASS", "E",
		"YDB-W-DBRNDWNBYPASS YottaDB database rundown may have been bypassed due to timeout - run MUPIP JOURNAL ROLLBACK" +
			" BACKWARD / MUPIP JOURNAL RECOVER BACKWARD / MUPIP RUNDOWN"},
	{-YDB_ERR_SIGACKTIMEOUT, "SIGACKTIMEOUT", "E", "Signal completion acknowledgement timeout: !AD"},
	{-YDB_ERR_SIGGORTNTIMEOUT, "ERR_SIGGORTNTIMEOUT", "W", "Shutdown of signal goroutines timed out"},
}
