// Code generated by go generate; DO NOT EDIT.

package yottadb

// #include "ydbconst.h"
import "C"

// Define constants exported by YottaDB
//
// Note: YDB_ERR_* error constants are defined in sub-package [pkg/lang.yottadb.com/go/yottadb/v2/ydberr].
const (
	// YottaDB Enum constants
	YDB_DEL_NODE               = C.YDB_DEL_NODE
	YDB_DEL_TREE               = C.YDB_DEL_TREE
	YDB_SEVERITY_ERROR         = C.YDB_SEVERITY_ERROR         /* Error - Something is definitely incorrect */
	YDB_SEVERITY_FATAL         = C.YDB_SEVERITY_FATAL         /* Fatal - Something happened that is so bad, YottaDB cannot continue */
	YDB_SEVERITY_INFORMATIONAL = C.YDB_SEVERITY_INFORMATIONAL /* Informational - won't see these returned as they continue running */
	YDB_SEVERITY_SUCCESS       = C.YDB_SEVERITY_SUCCESS       /* Success */
	YDB_SEVERITY_WARNING       = C.YDB_SEVERITY_WARNING       /* Warning - Something is potentially incorrect */
	YDB_DATA_ERROR             = C.YDB_DATA_ERROR
	YDB_DATA_NOVALUE_DESC      = C.YDB_DATA_NOVALUE_DESC /* Node has no value but has descendants */
	YDB_DATA_UNDEF             = C.YDB_DATA_UNDEF        /* Node is undefined */
	YDB_DATA_VALUE_DESC        = C.YDB_DATA_VALUE_DESC   /* Node has both value and descendants */
	YDB_DATA_VALUE_NODESC      = C.YDB_DATA_VALUE_NODESC /* Node has a value but no descendants */
	YDB_MAIN_LANG_C            = C.YDB_MAIN_LANG_C       /* Main routine written in C (or M) or is otherwise C-compatible */
	YDB_MAIN_LANG_GO           = C.YDB_MAIN_LANG_GO      /* Main routine is written in Go so handle signals differently */

	// General-purpose constants
	YDB_DEFER_HANDLER  = C.YDB_DEFER_HANDLER /* 0x7ffffffa - defer this signal handler (used in Go wrapper) */
	YDB_INT_MAX        = C.YDB_INT_MAX
	YDB_LOCK_TIMEOUT   = C.YDB_LOCK_TIMEOUT
	YDB_MAX_ERRORMSG   = C.YDB_MAX_ERRORMSG
	YDB_MAX_IDENT      = C.YDB_MAX_IDENT /* Maximum size of global/local name (not including '^') */
	YDB_MAX_M_LINE_LEN = C.YDB_MAX_M_LINE_LEN
	YDB_MAX_NAMES      = C.YDB_MAX_NAMES     /* Maximum number of variable names can be specified in a single ydb_*_s() call */
	YDB_MAX_PARMS      = C.YDB_MAX_PARMS     /* Maximum parameters to an M call (call-in) */
	YDB_MAX_STR        = C.YDB_MAX_STR       /* Maximum YottaDB string length */
	YDB_MAX_SUBS       = C.YDB_MAX_SUBS      /* Maximum subscripts currently supported */
	YDB_MAX_TIME_NSEC  = C.YDB_MAX_TIME_NSEC /* Max specified time in (long long) nanoseconds */
	YDB_MAX_YDBERR     = C.YDB_MAX_YDBERR    /* Maximum (absolute) value for a YottaDB error */
	YDB_MIN_YDBERR     = C.YDB_MIN_YDBERR    /* Minimum (absolute) value for a YottaDB error */
	YDB_NODE_END       = C.YDB_NODE_END
	YDB_NOTOK          = C.YDB_NOTOK
	YDB_NOTTP          = C.YDB_NOTTP
	YDB_OK             = C.YDB_OK      /* Successful return code */
	YDB_RELEASE        = C.YDB_RELEASE /* Corresponds to YottaDB release r1.24 (i.e. YDB_ZYRELEASE in sr_linux/release_name.h) */
	YDB_TP_RESTART     = C.YDB_TP_RESTART
	YDB_TP_ROLLBACK    = C.YDB_TP_ROLLBACK
)
