// Code generated by go generate; DO NOT EDIT.

// Creates C constants for every possible 'YDB_*' constant not defined in the installed version of YottaDB.
// This prevents unnecessary errors when compiling the matching .go constants.
// Constants not defined in the current version of YottaDB are assigned instead to an error message string
// so that the Go compiler creates an error only if the constant is invoked as if it existed (as an integer).

#include "libyottadb.h"

#define _YDB_ERROR_UNDEFINED "error code not defined by your YottaDB installation's libyottadb.h"


// Enum constants
// (#ifndef does not work on enums, so define them conditionally using the installed YDB release)

#if !defined(YDB_RELEASE) && !defined(YDB_DEL_TREE)  /* i.e. '#if YDB_RELEASE<120', except YDB_RELEASE was not defined until r1.24 so use this test instead */
  #define YDB_DEL_NODE _YDB_ERROR_UNDEFINED
  #define YDB_DEL_TREE _YDB_ERROR_UNDEFINED
  #define YDB_SEVERITY_ERROR _YDB_ERROR_UNDEFINED /* Error - Something is definitely incorrect */
  #define YDB_SEVERITY_FATAL _YDB_ERROR_UNDEFINED /* Fatal - Something happened that is so bad, YottaDB cannot continue */
  #define YDB_SEVERITY_INFORMATIONAL _YDB_ERROR_UNDEFINED /* Informational - won't see these returned as they continue running */
  #define YDB_SEVERITY_SUCCESS _YDB_ERROR_UNDEFINED /* Success */
  #define YDB_SEVERITY_WARNING _YDB_ERROR_UNDEFINED /* Warning - Something is potentially incorrect */
#elif YDB_RELEASE < 128
  #define YDB_DATA_ERROR _YDB_ERROR_UNDEFINED
  #define YDB_DATA_NOVALUE_DESC _YDB_ERROR_UNDEFINED /* Node has no value but has descendants */
  #define YDB_DATA_UNDEF _YDB_ERROR_UNDEFINED /* Node is undefined */
  #define YDB_DATA_VALUE_DESC _YDB_ERROR_UNDEFINED /* Node has both value and descendants */
  #define YDB_DATA_VALUE_NODESC _YDB_ERROR_UNDEFINED /* Node has a value but no descendants */
#elif YDB_RELEASE < 130
  #define YDB_MAIN_LANG_C _YDB_ERROR_UNDEFINED /* Main routine written in C (or M) or is otherwise C-compatible */
  #define YDB_MAIN_LANG_GO _YDB_ERROR_UNDEFINED /* Main routine is written in Go so handle signals differently */
#endif


#ifndef YDB_DEFER_HANDLER
  #define YDB_DEFER_HANDLER _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_INT_MAX
  #define YDB_INT_MAX _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_LOCK_TIMEOUT
  #define YDB_LOCK_TIMEOUT _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_MAX_ERRORMSG
  #define YDB_MAX_ERRORMSG _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_MAX_IDENT
  #define YDB_MAX_IDENT _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_MAX_M_LINE_LEN
  #define YDB_MAX_M_LINE_LEN _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_MAX_NAMES
  #define YDB_MAX_NAMES _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_MAX_PARMS
  #define YDB_MAX_PARMS _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_MAX_STR
  #define YDB_MAX_STR _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_MAX_SUBS
  #define YDB_MAX_SUBS _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_MAX_TIME_NSEC
  #define YDB_MAX_TIME_NSEC _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_MAX_YDBERR
  #define YDB_MAX_YDBERR _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_MIN_YDBERR
  #define YDB_MIN_YDBERR _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_NODE_END
  #define YDB_NODE_END _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_NOTOK
  #define YDB_NOTOK _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_NOTTP
  #define YDB_NOTTP _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_OK
  #define YDB_OK _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_RELEASE
  #define YDB_RELEASE _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_TP_RESTART
  #define YDB_TP_RESTART _YDB_ERROR_UNDEFINED
#endif

#ifndef YDB_TP_ROLLBACK
  #define YDB_TP_ROLLBACK _YDB_ERROR_UNDEFINED
#endif

