#!/bin/sh

if [ -z "$ydb_dist" ]; then
    ydb_dist=$(pkg-config --variable=prefix yottadb)
fi

cat <<EOF > error_codes.go
// Code generated by go generate; DO NOT EDIT.
package yottadb

const (
EOF
grep "#define YDB_ERR_" $ydb_dist/libydberrors*.h | awk '{print $2,"=",$3}' >> error_codes.go
echo "" >> error_codes.go
gcc -E $ydb_dist/libyottadb.h | grep YDB | tr ',' ' ' >> error_codes.go
cat <<EOF >> error_codes.go
YDB_OK = 0
)

EOF
